### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by JadeOfMaar** [JadeOfMaar/KipardSkylon#1]
* [x] All-black theme.
* [ ] Fix included custom Skylon wheels or fill in the cutaway sections in body pieces.
* [ ] Provide part upgrades to unlock TPS and advance drone core.
* [x] Check tech tree integration.
* [ ] Fix pre-made wheels, otherwise, fill in the cutaways on body pieces.
* [ ] Make wings use srf-attach so they can deployed in symmetry.
